updates

diff --git a/.github/workflows/owasp-dependencies-check.yml b/.github/workflows/owasp-dependencies-check.yml
--- a/.github/workflows/owasp-dependencies-check.yml
+++ b/.github/workflows/owasp-dependencies-check.yml
@@ -32,16 +32,16 @@ jobs:
         with:
           distribution: 'zulu'
           java-version: '17'
-      - name: Cache SonarCloud packages
+      - name: Cache for OWASP Vulnerabilities
+        id: cache-owasp-vulnerability-database
         uses: actions/cache@v4
         with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
+          key: cache-owasp-vulnerability-database
+          path: ~/.gradle/dependency-check-data/7.0
       - name: Check env variable
         run: >
           if [[ -z "${NVD_API_KEY}" ]]; then
-            echo "[FAILURE] Missing NVD_API_KEY env variable"
+            echo "[FAILURE] Missing NVD_API_KEY env variable" && exit 1
           else
             echo "[SUCCESS] NVD_API_KEY env variable exists"
           fi
